name: Publish Beta Version to Docker Hub

on:
  push:
    branches:
      - beta
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: beta
      - name: build
        run: |
          docker login -u fansys -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker build -t fansys/yapi:latest -t fansys/yapi:beta .
          docker build -t fansys/yapi:play-beta -f ./Dockerfile.web .
          docker push fansys/yapi:beta
          docker push fansys/yapi:play-beta
